Logic was implemented to update and remove users, and Bug fixed in ValidateUser inside 'middleware/validator.js' file
jestrade/api-make-it-real-2021 pull request #9
Opened 2021-04-29 18:00 UTC by cags84

- The schema was modified to receive the role parameter, this can be administrator 'admin' or registered.
- The authorization file was modified exactly the 'user Authorization' method to implement the required logic.
- For everything to work we have to create a service in 'api / services' with the name of userService.js where we place the logic to know if the user is an administrator or not.
- In userService.js we import the User model. and we consult the database with the id and with the condition if it is admin.
- functionality is implemented for you to save the role.
- Other minnor changes.

- Bug -> This error occurs when not all the required data is sent in the path 'api/users', by post method, then it generated an unexpected error, this bug was on line 84.

This error occurs when not all the required data is sent in the path 'api/users', by post method, then it generated an unexpected error, this bug was on line 84.

See error image.

<img width="582" alt="12" src="https://user-images.githubusercontent.com/88157/116596862-890bd600-a8ea-11eb-82ac-bf865add05ab.png">

After changing the line, this is the result.

<img width="589" alt="13" src="https://user-images.githubusercontent.com/88157/116596892-932dd480-a8ea-11eb-8d07-f9519066d0d2.png">

2021-04-29 19:18 UTC, cags84 commented
fix delete method in 'users / controllers' and update logic to implement delete method `commit 1ca89ad`

    - Updated locate file.
    - Other minnor changes.

2021-04-29 20:38 UTC, cags84 commented
Functionality was implemented to delete tweet (commit 3dbbc50)

- functionality was implemented to delete tweet, only to those who create it or to administrator users.

2021-04-30 01:15 UTC, jestrade requested changes
some minor comments

2021-04-30 01:15 UTC, jestrade commented on api/middleware/authorization.js
> +  const isAdminTemp = await isAdmin(userId);
puedes implementar el método isAdmin para que no sea una promesa y no requieras  el llamado de await, así lo puedes usar en el if (... && isAdmin).

2021-04-30 01:15 UTC, jestrade commented on api/middleware/authorization.js
> +  if (userId == id || isAdminTemp === true) {
Recuerda que cuando validas === true puedes omitir esa parte de la pregunta

2021-04-30 01:15 UTC, jestrade commented on api/middleware/authorization.js
> +    res.status(403).send("Operation not allowed!");
usar location

2021-04-30 01:15 UTC, jestrade commented on api/middleware/authorization.js
> +    res.status(403).send("Operation not allowed!");
usar location

2021-04-30 01:15 UTC, jestrade commented on api/middleware/authorization.js
> +  if (userId == id || isAdminTemp === true) {
lo mismo que arriba

2021-04-30 01:15 UTC, jestrade commented on api/middleware/validator.js
> +      errors.push("max characters exceded");
locale

2021-05-04 20:29 UTC, closed without merging